"""remove date from daily summaries

Revision ID: 1a89abec6f0a
Revises: f857f0a769dd
Create Date: 2025-07-21 01:10:43.228294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a89abec6f0a'
down_revision: Union[str, Sequence[str], None] = 'f857f0a769dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('daily_summaries', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('daily_summaries', 'created_at')
    # ### end Alembic commands ###
