"""remove sound and notifications in user settings

Revision ID: a2215e6debb9
Revises: 747197aaed8a
Create Date: 2025-07-20 02:07:38.474848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2215e6debb9'
down_revision: Union[str, Sequence[str], None] = '747197aaed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_summaries', 'breaks')
    op.drop_column('user_settings', 'notifications_enabled')
    op.drop_column('user_settings', 'sounds_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('sounds_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('daily_summaries', sa.Column('breaks', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
