"""add date

Revision ID: f3be2eab21e9
Revises: 1a89abec6f0a
Create Date: 2025-07-21 01:27:25.085326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3be2eab21e9'
down_revision: Union[str, Sequence[str], None] = '1a89abec6f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('daily_summaries', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('daily_summaries', 'date')
    # ### end Alembic commands ###
