"""remove duration_minutes

Revision ID: f857f0a769dd
Revises: a2215e6debb9
Create Date: 2025-07-20 23:20:10.714360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f857f0a769dd'
down_revision: Union[str, Sequence[str], None] = 'a2215e6debb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
